apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: nodetodo
    context: .
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - ./kubernetes-manifests/**.yaml
